# Generated by Django 3.0.2 on 2020-01-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_signupmodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='phone_number',
            field=models.CharField(max_length=14),
        ),
    ]
