# Generated by Django 3.0.2 on 2020-01-14 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_auto_20200113_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupmodel',
            name='password',
        ),
    ]
